# Generated by Django 4.2.21 on 2025-05-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0003_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_image', models.FileField(upload_to='cimage/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icoms.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icoms.profile')),
            ],
        ),
    ]
