# Generated by Django 4.2.21 on 2025-06-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0004_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
