# Generated by Django 4.2.21 on 2025-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0006_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('video', models.FileField(upload_to='reels/')),
            ],
        ),
        migrations.DeleteModel(
            name='Shot',
        ),
    ]
