# Generated by Django 4.2.21 on 2025-06-10 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0007_reel_delete_shot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('captions', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
    ]
