# Generated by Django 4.2.21 on 2025-06-10 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0008_reels_delete_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
