# Generated by Django 4.2.21 on 2025-06-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0009_alter_reels_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='image',
            field=models.FileField(upload_to='reels'),
        ),
    ]
