# Generated by Django 4.2.21 on 2025-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0010_alter_reels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
