# Generated by Django 4.2.21 on 2025-07-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0015_profile_post_alter_profile_bio_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
