# Generated by Django 4.2.21 on 2025-07-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0017_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
