# Generated by Django 4.2.21 on 2025-07-19 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icoms', '0018_remove_profile_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comments_user',
        ),
        migrations.AddField(
            model_name='comments',
            name='reply_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
