# Generated by Django 4.2.21 on 2025-07-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0019_rename_comments_comments_comments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='users',
        ),
    ]
