# Generated by Django 4.2.21 on 2025-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0021_profile_followers_count_profile_following_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_user',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='follow_user',
            name='datatime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
