# Generated by Django 4.2.21 on 2025-07-30 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icoms', '0024_alter_follow_user_followers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mimage')),
                ('video', models.FileField(blank=True, null=True, upload_to='mvideo')),
                ('datetime', models.DateField(auto_now_add=True)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otheruser', to=settings.AUTH_USER_MODEL)),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
