# Generated by Django 4.2.21 on 2025-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0025_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
