# Generated by Django 4.2.21 on 2025-08-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0026_message_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
