# Generated by Django 4.2.21 on 2025-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0027_alter_message_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
