# Generated by Django 4.2.21 on 2025-08-11 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icoms', '0028_comments_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reels',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reels_video'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='captions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reels',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reels',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reels_image'),
        ),
    ]
