# Generated by Django 4.2.21 on 2025-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0029_reels_user_reels_video_alter_reels_captions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reels_image'),
        ),
    ]
