# Generated by Django 4.2.23 on 2025-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0032_alter_comments_id_alter_follow_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_user',
            name='datatime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
