# Generated by Django 4.2.23 on 2025-09-03 13:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoms', '0033_alter_follow_user_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='mimage'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mvideo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='postimage/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='postvideo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile_image/'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='reels_image'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='reels_video'),
        ),
    ]
